spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9f0bd8ec9abb91a24b05
            clientSecret: 37ce0c621db7a9f0c9eefc5f9405a0a564ac5ac5
            scope: user


# spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/cycle-data'
    username: bibhu04
    password: bibhu04
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub